-- Sessões bloqueadas e o comando da sessão bloqueadora.
-- Origem: Checklist de problemas de performance - Service Desk Sankhya.

SELECT S.BLOCKING_INSTANCE AS INST_BLOQUEADOR,
S.BLOCKING_SESSION AS SID_BLOQUEADOR,
(SELECT SQL_FULLTEXT
FROM V$SQL
WHERE SQL_ID = B.SQL_ID AND ROWNUM = 1)
AS COMANDO_BLOQUEADOR,
(SELECT CLIENT_INFO
FROM V$SESSION S1
WHERE S1.SID = B.SID AND ROWNUM = 1)
AS INFO_BLOQUEADOR,
S.INST_ID,
S.SCHEMANAME,
S.SID,
P.SPID PID_LINUX,
S.SERIAL#,
S.STATUS,
S.MODULE,
S.MACHINE,
S.USERNAME,
S.COMMAND,
(SELECT SQL_FULLTEXT
FROM V$SQL
WHERE SQL_ID = S.SQL_ID AND ROWNUM = 1)
AS COMANDO,
S.OSUSER,
TO_CHAR (S.LOGON_TIME, 'DD/MM/YYYY HH24:MI') AS LOGON_TIME,
S.LAST_CALL_ET,
S.WAIT_CLASS
FROM GV$SESSION S, GV$PROCESS P, V$SESSION B
WHERE P.ADDR = S.PADDR
AND B.SID = S.BLOCKING_SESSION
AND S.BLOCKING_SESSION IS NOT NULL
--and upper(s.MACHINE) like '%RH-LOC-10%'
ORDER BY 1 ASC;
